chore: cleanup scripts

diff --git a/.bin/bash_create b/.bin/bash_create
--- a/.bin/bash_create
+++ b/.bin/bash_create
@@ -9,7 +9,7 @@ if [[ -f "$target_file" ]]; then
 fi
 
 echo "#!/bin/bash" >> "$target_file"
-echo "set -euxo pipefail" >> "$target_file"
+echo "set -eo pipefail" >> "$target_file"
 chmod +x "$target_file"
 
 if [[ "$2" = "yadm" ]]; then
